### ISSUE TITLE
write up draft proposal

### ISSUE THREAD

**Issue by aromatic-toast** [UBC-MDS/DSCI522_309#4]
proposal components 

1. [data here](https://archive.ics.uci.edu/ml/datasets/Online+Shoppers+Purchasing+Intention+Dataset)

2. predictive question: predict buy/no buy based on webpage analytics

3. wait on this till after EDA is done 

4. describe the  table and the figure that is made based on EDA

5. tables of the following: confusion matrix, ROC curce, F1 score, predictor importance

**Comment by vermashivam679** [comment]
Related to point 3 above, I have noted down some action items we can try

We plan to preprocess that data before building a classification model due to various reasons:
- The percentile distribution of the explanatory variables looks skewed (for e.g. 75% of the data has `PageValues` as 0). We need to study how this will affect our modeling.
- Standardize/Normalize variables because variables have very different scales.
- Merge different categories of categorical variables to balance the categories. For e.g. `OperatingSystems` variable with categories [4,5,6,7] constitute ~5% of the data, so it makes more sense to club these categories.
- Since the target variable has only 15% of positive responses, we need to find ways to tackle class imbalance in the response variable.
- Decide a methodology on how to do outlier treatment & feature selection.

**Comment by aromatic-toast** [comment]
do we know at this point which classification approach we would use? or perhaps a list of methods? Logistic classifier, SVM, decision tree etc?
